import { basename, dirname, extname } from "node:path";

export const sourceExclusionReasons = [
  "lock_file",
  "generated_file",
  "generated_bundle",
  "generated_output",
  "translated_locale",
  "binary",
  "non_utf8",
  "empty",
  "oversized",
  "snapshot",
  "minified",
  "static_asset",
  "vendored_dependency",
] as const;

export type SourceExclusionReason = (typeof sourceExclusionReasons)[number];

export interface ClassifiableSourceFile {
  path: string;
  size: number;
}

export type SourceFileClassification =
  | { status: "admitted" }
  | { status: "excluded"; reason: SourceExclusionReason };

export interface SourceFileClassificationOptions {
  canonicalLocale?: string;
}

const admitted: SourceFileClassification = { status: "admitted" };
const localeCatalogExtensions = new Set([
  ".json",
  ".yaml",
  ".yml",
  ".po",
  ".pot",
  ".properties",
]);
const lockFileNames = new Set([
  "bun.lock",
  "bun.lockb",
  "cargo.lock",
  "chart.lock",
  "composer.lock",
  "gemfile.lock",
  "npm-shrinkwrap.json",
  "package-lock.json",
  "pipfile.lock",
  "pnpm-lock.yaml",
  "poetry.lock",
  "uv.lock",
  "yarn.lock",
]);
const vendoredDirectoryNames = new Set([
  "node_modules",
  "third-party",
  "third_party",
  "vendor",
  "vendors",
]);
const generatedOutputDirectoryNames = new Set([
  ".cache",
  ".next",
  ".nuxt",
  ".parcel-cache",
  ".svelte-kit",
  ".turbo",
  "build",
  "coverage",
  "dist",
  "generated",
  "out",
  "target",
]);

/**
 * Classifies paths using repository-wide evidence. Content-based generated-file
 * detection is intentionally separate so callers can avoid reading files that
 * are already excluded by safe path rules.
 */
export function classifySourceFilePaths(
  files: readonly ClassifiableSourceFile[],
  options: SourceFileClassificationOptions = {},
): ReadonlyMap<string, SourceFileClassification> {
  const normalizedPaths = new Set(
    files.map((file) => normalizePath(file.path)),
  );
  const translatedLocales = findTranslatedLocaleCatalogs(
    files,
    options.canonicalLocale ?? "en-US",
  );
  const classifications = new Map<string, SourceFileClassification>();

  for (const file of files) {
    const path = normalizePath(file.path);
    const pathSegments = path.toLowerCase().split("/");
    const filename = basename(path).toLowerCase();
    const extension = extname(filename).toLowerCase();

    let classification = admitted;
    if (isLockOrCacheFile(filename, extension)) {
      classification = exclude("lock_file");
    } else if (
      pathSegments.some((segment) => vendoredDirectoryNames.has(segment))
    ) {
      classification = exclude("vendored_dependency");
    } else if (
      pathSegments.some((segment) => generatedOutputDirectoryNames.has(segment))
    ) {
      classification = exclude("generated_output");
    } else if (isSnapshot(pathSegments, filename)) {
      classification = exclude("snapshot");
    } else if (isMinified(filename)) {
      classification = exclude("minified");
    } else if (extension === ".svg") {
      classification = exclude("static_asset");
    } else if (isGeneratedApiBundle(path, normalizedPaths)) {
      classification = exclude("generated_bundle");
    } else if (translatedLocales.has(path)) {
      classification = exclude("translated_locale");
    }

    classifications.set(file.path, classification);
  }

  return classifications;
}

/** Inspect only a bounded header; never requires logging or retaining content. */
export function classifySourceFileHeader(
  content: string,
): SourceFileClassification {
  const header = content.slice(0, 2_048).split("\n").slice(0, 20).join("\n");
  const commentPrefix = String.raw`(?:\/\/|#|\/\*+|\*|<!--)`;
  const generated = String.raw`(?:@generated|<auto-generated>|generated (?:file|code|by)|code generated|(?:this )?(?:file|code) (?:is |was )?auto(?:matically)?[- ]?generated|auto(?:matically)?[- ]?generated (?:file|code))`;
  const doNotEdit = String.raw`(?:do not edit|do not modify|do not edit this file|do not edit manually)`;
  const strongGeneratedMarker = new RegExp(
    String.raw`(?:^|\n)\s*${commentPrefix}[^\n]{0,160}(?:${generated})(?:[^\n]{0,160}(?:${doNotEdit}))?`,
    "iu",
  );
  const strongDoNotEditMarker = new RegExp(
    String.raw`(?:^|\n)\s*${commentPrefix}[^\n]{0,160}(?:please\s+)?do not (?:edit|modify)(?: this file| manually)?(?:[.!—-]|$)`,
    "iu",
  );

  return strongGeneratedMarker.test(header) ||
    strongDoNotEditMarker.test(header)
    ? exclude("generated_file")
    : admitted;
}

function exclude(reason: SourceExclusionReason): SourceFileClassification {
  return { status: "excluded", reason };
}

function normalizePath(path: string): string {
  return path.replaceAll("\\", "/").replace(/^\.\//u, "");
}

function isLockOrCacheFile(filename: string, extension: string): boolean {
  return (
    extension === ".lock" ||
    extension === ".cache" ||
    lockFileNames.has(filename) ||
    filename === ".eslintcache" ||
    filename === ".stylelintcache"
  );
}

function isSnapshot(
  pathSegments: readonly string[],
  filename: string,
): boolean {
  return (
    pathSegments.includes("__snapshots__") ||
    filename.endsWith(".snap") ||
    /\.snapshot\.[^.]+$/iu.test(filename)
  );
}

function isMinified(filename: string): boolean {
  return /\.min\.(?:c?js|mjs|css)$/iu.test(filename);
}

function isGeneratedApiBundle(
  path: string,
  repositoryPaths: ReadonlySet<string>,
): boolean {
  const filename = basename(path).toLowerCase();
  if (!/^(?:openapi|swagger)\.(?:json|ya?ml)$/u.test(filename)) {
    return false;
  }

  const directory = dirname(path) === "." ? "" : `${dirname(path)}/`;
  const sourceRoot = `${directory}src/`;
  const hasSourceEntry = [...repositoryPaths].some((candidate) =>
    new RegExp(
      `^${escapeRegExp(sourceRoot)}(?:openapi|swagger)\\.(?:json|ya?ml)$`,
      "iu",
    ).test(candidate),
  );
  const hasModularSources = [...repositoryPaths].some(
    (candidate) =>
      candidate.startsWith(`${sourceRoot}paths/`) ||
      candidate.startsWith(`${sourceRoot}components/`),
  );

  return hasSourceEntry && hasModularSources;
}

interface LocaleCatalog {
  path: string;
  locale: string;
  group: string;
}

function findTranslatedLocaleCatalogs(
  files: readonly ClassifiableSourceFile[],
  canonicalLocale: string,
): ReadonlySet<string> {
  const groups = new Map<string, LocaleCatalog[]>();
  for (const file of files) {
    const catalog = parseLocaleCatalog(file.path);
    if (!catalog) {
      continue;
    }
    const group = groups.get(catalog.group) ?? [];
    group.push(catalog);
    groups.set(catalog.group, group);
  }

  const normalizedCanonical = normalizeLocale(canonicalLocale);
  const translated = new Set<string>();
  for (const catalogs of groups.values()) {
    const canonical = catalogs.filter(
      (catalog) => normalizeLocale(catalog.locale) === normalizedCanonical,
    );
    if (canonical.length !== 1 || catalogs.length < 2) {
      continue;
    }
    for (const catalog of catalogs) {
      if (catalog !== canonical[0]) {
        translated.add(catalog.path);
      }
    }
  }
  return translated;
}

function parseLocaleCatalog(pathInput: string): LocaleCatalog | null {
  const path = normalizePath(pathInput);
  const segments = path.split("/");
  const localeRootIndex = segments.findIndex((segment) =>
    /^(?:locale|locales|translations)$/iu.test(segment),
  );
  if (localeRootIndex < 0) {
    return null;
  }

  const remainder = segments.slice(localeRootIndex + 1);
  if (remainder.length === 0) {
    return null;
  }
  const root = segments.slice(0, localeRootIndex + 1).join("/");
  const first = remainder[0];
  if (!first) {
    return null;
  }

  if (remainder.length === 1) {
    const extension = extname(first).toLowerCase();
    const locale = basename(first, extension);
    if (
      !localeCatalogExtensions.has(extension) ||
      !isLocaleIdentifier(locale)
    ) {
      return null;
    }
    return { path, locale, group: `${root}/<locale>${extension}` };
  }

  if (!isLocaleIdentifier(first)) {
    return null;
  }
  const tail = remainder.slice(1).join("/");
  const extension = extname(tail).toLowerCase();
  if (!localeCatalogExtensions.has(extension)) {
    return null;
  }
  return { path, locale: first, group: `${root}/<locale>/${tail}` };
}

function isLocaleIdentifier(value: string): boolean {
  return /^[a-z]{2,3}(?:[-_][a-z]{4})?(?:[-_](?:[a-z]{2}|[0-9]{3}))$/iu.test(
    value,
  );
}

function normalizeLocale(value: string): string {
  return value.replaceAll("_", "-").toLowerCase();
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}
