import { describe, expect, test } from "bun:test";

import {
  classifySourceFileHeader,
  classifySourceFilePaths,
  type ClassifiableSourceFile,
  type SourceExclusionReason,
} from "./source-file-classification";

describe("source-file classification", () => {
  test.each([
    ["pnpm-lock.yaml", "lock_file"],
    ["apps/web/i18n.lock", "lock_file"],
    ["node_modules/library/index.js", "vendored_dependency"],
    ["vendor/library/index.js", "vendored_dependency"],
    ["dist/index.js", "generated_output"],
    ["apps/web/.next/server.js", "generated_output"],
    ["packages/api/.cache/result.json", "generated_output"],
    ["src/__snapshots__/component.ts.snap", "snapshot"],
    ["public/application.min.js", "minified"],
    ["assets/company-logo.svg", "static_asset"],
  ] satisfies ReadonlyArray<readonly [string, SourceExclusionReason]>)(
    "excludes %s as %s",
    (path, reason) => {
      expect(classify([file(path)]).get(path)).toEqual({
        status: "excluded",
        reason,
      });
    },
  );

  test("excludes a strong generated marker only from the bounded header", () => {
    expect(
      classifySourceFileHeader(
        "// Code generated by schema-tool. DO NOT EDIT.\nexport const value = 1;",
      ),
    ).toEqual({ status: "excluded", reason: "generated_file" });
    expect(
      classifySourceFileHeader(
        "# DO NOT EDIT.\nsetting: generated-by-an-external-tool",
      ),
    ).toEqual({ status: "excluded", reason: "generated_file" });
    expect(
      classifySourceFileHeader(
        `${"x".repeat(2_100)}\n// Code generated by a sentence deep in the file. DO NOT EDIT.`,
      ),
    ).toEqual({ status: "admitted" });
  });

  test("does not treat ordinary auto-generated runtime values as a generated file", () => {
    expect(
      classifySourceFileHeader(
        "/**\n * @param block block data whose id is auto-generated\n */\nexport function add(block: object) {}",
      ),
    ).toEqual({ status: "admitted" });
  });

  test("retains a canonical en-US locale and excludes translated siblings", () => {
    const files = [
      file("apps/web/locales/en-US.json"),
      file("apps/web/locales/de-DE.json"),
      file("apps/web/locales/fr-FR.json"),
      file("apps/web/locales/zh-Hans-CN.json"),
      file("packages/ui/locales/en-US/messages.json"),
      file("packages/ui/locales/es-ES/messages.json"),
    ];
    const result = classify(files);

    expect(result.get(files[0]!.path)).toEqual({ status: "admitted" });
    expect(result.get(files[1]!.path)).toEqual({
      status: "excluded",
      reason: "translated_locale",
    });
    expect(result.get(files[2]!.path)).toEqual({
      status: "excluded",
      reason: "translated_locale",
    });
    expect(result.get(files[4]!.path)).toEqual({
      status: "admitted",
    });
    expect(result.get(files[5]!.path)).toEqual({
      status: "excluded",
      reason: "translated_locale",
    });
    expect(result.get(files[3]!.path)).toEqual({
      status: "excluded",
      reason: "translated_locale",
    });
  });

  test("keeps locale catalogs when no canonical locale is confidently present", () => {
    const files = [file("locales/de-DE.json"), file("locales/fr-FR.json")];
    const result = classify(files);

    expect(result.get(files[0]!.path)).toEqual({ status: "admitted" });
    expect(result.get(files[1]!.path)).toEqual({ status: "admitted" });
  });

  test("excludes an OpenAPI bundle only with modular source-of-truth evidence", () => {
    const generatedBundle = [
      file("docs/api/openapi.yml"),
      file("docs/api/src/openapi.yml"),
      file("docs/api/src/paths/users.yml"),
    ];
    expect(classify(generatedBundle).get(generatedBundle[0]!.path)).toEqual({
      status: "excluded",
      reason: "generated_bundle",
    });

    const authoredBundle = file("docs/api-v2/openapi.yml");
    expect(classify([authoredBundle]).get(authoredBundle.path)).toEqual({
      status: "admitted",
    });
  });

  test.each([
    "package.json",
    "pnpm-workspace.yaml",
    "turbo.json",
    "deploy/values.yaml",
    "docs/authored.json",
    "src/large-authored.ts",
    "src/service.test.ts",
    "packages/database/migrations/001.sql",
    "AGENTS.md",
    "src/ambiguous.data",
  ])("keeps %s by default", (path) => {
    expect(classify([file(path)]).get(path)).toEqual({ status: "admitted" });
  });
});

function file(path: string): ClassifiableSourceFile {
  return { path, size: 100 };
}

function classify(files: readonly ClassifiableSourceFile[]) {
  return classifySourceFilePaths(files);
}
